package model.Dao;

import java.sql.Connection;
import java.util.List;

import model.Dto.AdminRecipeDto;

public interface AdminRecipeDao {
	String SelectAllSql = " SELECT * FROM ADMIN_RECIPE ";
			
			
	
	String InsertSql = " INSERT INTO ADMIN_RECIPE VALUES(ADMIN_RECIPE_SEQ.NEXTVAL,(SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NO=?),?, ?, ?, ?, SYSDATE,0,'N',DEFAULT,?,?,?) ";
	String DeletSql = " DELETE FROM ADMIN_RECIPE WHERE RECIPE_NO=? ";
	String UpdateSql = " UPDATE ADMIN_RECIPE SET RECIPE_TITLE=?, RECIPE_INGREDIENT=?, RECIPE_RECIPE_TEXT=?, RECIPE_IMAGE_NAME=?,  RECIPE_IMAGE_REALNAME=?, RECIPE_IMAGE_UPLOADPATH=? WHERE RECIPE_NO=? ";
	String SelectOneSql = " SELECT * FROM ADMIN_RECIPE WHERE RECIPE_NO =? ";
	
	String addHits = " UPDATE ADMIN_RECIPE SET BOARD_HITS = BOARD_HITS + 1 WHERE RECIPE_NO=? ";
	
	
	String countSql	 = " SELECT COUNT(*) FROM USERBOARD_INFO ";
	
	String addAnswer = " INSERT INTO ANSWER_ADMIN_RECIPE VALUES((SELECT RECIPE_NO FROM ADMIN_RECIPE WHERE RECIPE_NO=?),ANSWER_USERRECIPE_SEQ.NEXTVAL,?,?, SYSDATE) ";
	String answerList = " SELECT * FROM ANSWER_ADMIN_RECIPE WHERE RECIPE_NO = ? ";
	String deleteAnswer = " DELETE FROM ANSWER_ADMIN_RECIPE WHERE RECIPE_NO=(SELECT RECIPE_NO FROM ADMIN_RECIPE WHERE RECIPE_NO=?)  AND ANSWER_NO=? ";
	String answerSelectOne = " SELECT * FROM ANSWER_ADMIN_RECIPE WHERE RECIPE_NO=(SELECT RECIPE_NO FROM ADMIN_RECIPE WHERE RECIPE_NO=?)  AND ANSWER_NO=? ";
	String updateAnswer = " UPDATE ANSWER_ADMIN_RECIPE SET ANSWER_WRITER=?, ANSWER_CONTENTE=? WHERE RECIPE_NO=(SELECT RECIPE_NO FROM ADMIN_RECIPE WHERE RECIPE_NO=?)  AND ANSWER_NO=? ";
	
	
	String save = " UPDATE ADMIN_RECIPE SET BOARD_SAVE='Y' WHERE RECIPE_NO=? ";
	
	
	
	String bestRecipeSql = " SELECT * FROM ( SELECT RECIPE_NO, MEMBER_NO, RECIPE_TITLE, ROWNUM RNO FROM ADMIN_RECIPE ORDER BY BOARD_HITS DESC ) WHERE RNO < 4 ";

	public List<AdminRecipeDto> admin_bestRecipe(Connection con);
}
